# Generated by Django 5.1.1 on 2024-09-12 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_borrow_borrow_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default='aaa'),
            preserve_default=False,
        ),
    ]
